name: Publish Retype powered website to GitHub Pages
on:
  push:
    paths:
      - 'frinx-uniconfig/release-notes/index.md'

  workflow_dispatch:

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@v2.4.0
        with:
          license: ${{ secrets.RETYPE_SECRET }}

      - uses: retypeapp/action-github-pages@v2.3.0
        with:
          update-branch: true
